/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fullmadagilists.api2semestre.telas;

import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author pitag
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        SimboloLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 35, 57));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha:");
        jLabel1.setMinimumSize(new java.awt.Dimension(69, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        txtNomeUsuario.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        txtNomeUsuario.setPreferredSize(new java.awt.Dimension(480, 60));
        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 286, -1, -1));

        txtSenhaUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtSenhaUsuario.setMinimumSize(new java.awt.Dimension(480, 60));
        txtSenhaUsuario.setPreferredSize(new java.awt.Dimension(480, 60));
        txtSenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        btnEntrar.setBackground(new java.awt.Color(152, 204, 255));
        btnEntrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\pitag\\Documents\\NetBeansProjects\\API-2-Semestre\\src\\main\\java\\com\\fullmadagilists\\api2semestre\\telas\\Botao Acessar (1).png")); // NOI18N
        btnEntrar.setBorderPainted(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 482, -1, -1));

        SimboloLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\pitag\\Documents\\NetBeansProjects\\API-2-Semestre\\src\\main\\java\\com\\fullmadagilists\\api2semestre\\telas\\Group 6.png")); // NOI18N
        jPanel1.add(SimboloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 32, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuário:");
        jLabel4.setMinimumSize(new java.awt.Dimension(69, 20));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 258, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 850, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
       /* try {
            String nome_usuario, senha_usuario;
            nome_usuario = txtNomeUsuario.getText();
            senha_usuario = txtSenhaUsuario.getText();
            Usuario usuario = new Usuario();
            usuario.setNome_usuario(nome_usuario);
            usuario.setSenha_usuario(senha_usuario);
            
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            ResultSet rsUsuarioDAO = usuarioDAO.autenticacaoUsuario(usuario);
            
            if(rsUsuarioDAO.next()){
                JOptionPane.showMessageDialog(null, "DEU CERTO");
            }else{
                JOptionPane.showMessageDialog(null, "DEU ERRO");
            }
                
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtSenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SimboloLogin;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JPasswordField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
